### ISSUE TITLE
hamster integration doesn't have ubuntu "xenial" support 

### ISSUE THREAD

**Issue by ple-unity** [tsarnowski/hamster#5]
After upgrade my ubuntu to xenial, there are not avaiable packages to "xenial".

It is working with "wily" version, but it should follow ubuntu release cycles :-)

**Comment by tsarnowski** [comment]
For now You can try https://launchpad.net/~sarnowskitomek/+archive/ubuntu/hamter-intergration-beta, I tested it on fresh Xubuntu 16.04 install and it works. If I get second confirmation I publish new packages to stable PPA.

**Comment by ple-unity** [comment]
after adding this test ppa, everything works perfectly under xenial

**Comment by tsarnowski** [comment]
Packages published to stable ppa too.
