### ISSUE TITLE
Autocomplete of jira issues not working on ubuntu 17.04

### ISSUE THREAD

**Issue by tsarnowski** [tsarnowski/hamster#6]

**Comment by ple-unity** [comment]
1. Hamster version: 2.2.0
2. dpkg -l | grep python in attachment
[python.txt](https://github.com/tsarnowski/hamster/files/989444/python.txt)

3. system was upgraded from previous versions

**Comment by tsarnowski** [comment]
Pleas show result of:  python --version

**Comment by tsarnowski** [comment]
Closing because no response for long time.
